Render index markdowns for docs resources; add minimal repo-schema wi…
onflow/next-docs-v1 pull request #230
Opened 2022-06-20 19:51 UTC by codingone21

Rendering `index` paths for the repositories with /docs sources, other than /cadence, which is already configured.

**flow-go-sdk**

![flow-go-sdk-mdx-fail](https://user-images.githubusercontent.com/18616121/174669164-253a1b8b-f963-4d4b-87d3-7ba9b0eed807.png)

**fcl-js**

![fcl-js-rendered](https://user-images.githubusercontent.com/18616121/174669162-a75fa256-6052-48f6-ad98-b2f48c0a04da.png)

**fcl-js-testing**
(NOTE: Hyperlink in 'installation' is not highlighted! The link still works though)
![flow-js-testing-rendered-need-to-highlight-link](https://user-images.githubusercontent.com/18616121/174669166-5bd14979-bb68-4933-bfe1-c3384dbb0987.png)

**flow/../kitty-items**

![flow-kitty-items-rendered](https://user-images.githubusercontent.com/18616121/174669167-efcd51ab-2110-480b-9619-19e34b557019.png)

**flow/../vscode-extension**

![flow-vscode-ext-rendered](https://user-images.githubusercontent.com/18616121/174669168-b00ef039-4d13-43f6-b915-7e3a48f8b224.png)

2022-06-21 18:59 UTC, 10thfloor requested changes

2022-06-21 18:59 UTC, 10thfloor commented on app/cms/github.server.ts
> +    : `docs/${fileOrDirPath}`
Something like that...

2022-06-22 16:21 UTC, codingone21 commented on app/cms/github.server.ts
> +    : `docs/${fileOrDirPath}`
This could work!

2022-06-22 22:14 UTC, 10thfloor commented on app/cms/github.server.ts
> +    : `docs/${fileOrDirPath}`
@codingone21 Any updates on this?

2022-06-23 13:53 UTC, codingone21 commented on app/cms/github.server.ts
> +    : `docs/${fileOrDirPath}`
Yep! Just refactored the code and pushed to this branch. The videos aren't rendering for me, but that might be related to the more recent changes on the main branch

2022-06-23 15:06 UTC, codingone21 commented on app/routes/$repo.tsx
> -  temporarilyRedirectToComingSoon()
should I keep this line `temporarilyRedirectToComingSoon()`  ? Not sure if we are going to push to prod as we continue developing

2022-06-23 18:51 UTC, 10thfloor approved these changes

2022-06-23 18:51 UTC, 10thfloor approved these changes

2022-06-23 18:51 UTC, merged