Update internal page layout
onflow/next-docs-v1 pull request #371
Opened 2022-07-01 15:51 UTC by joekrill

This updates and simplifies the `InternalPage` layout to the desired design for desktop. The heights of the sidebars are now calculated based on the actual height/position of the navbar as opposed to hard-coding expected heights. 

Also adds a few utilities:

- `canUseDOM` can be used to determine if the DOM is available (i.e. are we server-side rendering?)
- `useIsomorphicLayoutEffect` a `useLayoutEffect` replacement that can be safely used when server-side rendering.
- `useResizeObserver` provides the ability to watch an element for resize events in a performant way.

Will follow this up with mobile features as described in #368

2022-07-01 18:19 UTC, aureentuluvacal approved these changes
This is awesome. I think instead of using the word "shared" for the resize observer, you could use "singleton". That's totally a nitpick though.

2022-07-04 15:49 UTC, 10thfloor requested changes
This looks great. I think we should move the new hooks out of the design system, and into the main app.

2022-07-05 12:50 UTC, joekrill commented
> This looks great. I think we should move the new hooks out of the design system, and into the main app.

I'm not totally sure how this would work because the design system components have direct dependencies on those hooks. So we'd then need to introduce some sort of dependency injection or something similar to make them available to the underlying components. They're also fairly generic -- they're not really specific to the app code.

2022-07-05 16:22 UTC, schpet approved these changes
lgtm 👍🏻

2022-07-05 16:23 UTC, schpet commented
@10thfloor re-requesting your review here given [Joe's comment](https://github.com/onflow/next-docs-v1/pull/371#issuecomment-1175022523)

2022-07-05 17:27 UTC, 10thfloor approved these changes

2022-07-05 17:27 UTC, merged