Internal components
onflow/next-docs-v1 pull request #40
Opened 2022-05-19 15:45 UTC by alse

Additional internal components from #3:

Tables, Callouts, Lower page nav, Breadcrumbs, Internal version select, Internal sidebar menu

2022-05-19 16:56 UTC, aureentuluvacal requested changes
Works fantastically. Just have one callout. I'll make sure my storybook stories are just as clean lol

2022-05-19 16:56 UTC, aureentuluvacal commented on libs/design-system/src/lib/Components/InternalVersionSelect/InternalVersionSelect.stories.tsx
> +dark.parameters = {
```suggestion
dark.args = {
  versions: VERSIONS,
  selectedVersionName: VERSIONS[0].name,
};
dark.parameters = {
```

2022-05-19 17:17 UTC, alse commented
@aureentuluvacal thanks, updated!

2022-05-20 14:19 UTC, alse commented
Contents were moved to https://github.com/onflow/next-docs-v2/pull/2, closing

2022-05-20 14:19 UTC, closed without merging