Page Content 2 Column Link Card
onflow/next-docs-v1 pull request #55
Opened 2022-05-26 20:22 UTC by joekrill

# Adds 2 Column Link Card

<img width="1547" alt="Screen Shot 2022-05-26 at 1 50 38 PM" src="https://user-images.githubusercontent.com/393220/170572744-8133f53e-c661-405f-b85a-451fd8b85991.png">

Mobile:
<img width="200px" src="https://user-images.githubusercontent.com/393220/170573509-ee6bc1af-1686-47af-b5eb-62c1386eca78.png">

Note: I moved the tags below the title based on the discussion from yesterday.

---

Closes #44

2022-05-27 19:21 UTC, alse requested changes
@joekrill , I just left some small suggestions. Looks like my tailwind container updates didn't make it in the last one, it should fix some responsive issues. I opened a new pr with it: #59

2022-05-31 14:07 UTC, joekrill commented on libs/design-system/src/lib/Components/LinkCard2Column/index.tsx
> +      <div className="flex flex-1 flex-col items-stretch">
Not sure I totally understand.  These should be full width in those cases already, I believe.  Do you mean the outer card should continue to stack vertically at `md` and not switch to horizontal until `lg` (i.e. replace `md:flex-row` with `lg:flex-row` on the container)?

2022-05-31 14:19 UTC, joekrill commented
I think I've got all the changes covered. I had to rebase and force-push so hopefully that didn't cause any problems. 

It's not clear from the designs what the hover styles are supposed to be (are they specified somewhere in particular that maybe I'm missing?). In dark mode, in particular, the drop shadow on hover of the "items" is hardly noticeable so there isn't much of a hover effect (I'm hovering the top Item in this shot):

 
<img width="314" alt="Screen Shot 2022-05-31 at 10 14 57 AM" src="https://user-images.githubusercontent.com/393220/171195950-c0486e5f-c6e0-4975-9481-f8716df3c587.png">


While in light mode it's much more clear:

<img width="383" alt="Screen Shot 2022-05-31 at 10 17 24 AM" src="https://user-images.githubusercontent.com/393220/171195967-ba7c3584-a904-47f9-9e55-8e524a78d104.png">

Should there be an adjustment made for dark mode hover?

2022-05-31 17:23 UTC, 10thfloor approved these changes

2022-05-31 17:24 UTC, 10thfloor commented on libs/design-system/src/lib/Components/LinkCard2Column/LinkCard2Column.stories.tsx
> +    {
Same comment about interfaces per the "3 column PR"

2022-05-31 17:39 UTC, alse commented on libs/design-system/src/lib/Components/LinkCard2Column/index.tsx
> +      <div className="flex flex-1 flex-col items-stretch">
Ah it only showed up with the container changes from #59 . Not a big deal though, can merge this in

2022-05-31 18:00 UTC, alse approved these changes

2022-05-31 18:08 UTC, merged