Page Content 3 Column Link Card
onflow/next-docs-v1 pull request #68
Opened 2022-05-31 14:34 UTC by joekrill

# Adds 3 Column Link Card

Light:

<img width="1199" alt="Screen Shot 2022-05-31 at 10 28 10 AM" src="https://user-images.githubusercontent.com/393220/171198173-89609a3c-9603-4c4f-83ee-e80747cbd53c.png">

Dark:

<img width="1198" alt="Screen Shot 2022-05-31 at 10 28 16 AM" src="https://user-images.githubusercontent.com/393220/171198193-f86d22f7-0748-493b-8b6c-c3789d6cc75d.png">

Mobile:

<img width="307" alt="Screen Shot 2022-05-31 at 10 28 25 AM" src="https://user-images.githubusercontent.com/393220/171198247-38109c66-caf8-4608-8974-a4b43da74f83.png">

I had to add some custom CSS to handle how the borders needed to look and interact with the hover states. I tried to get around it using other method (using the `peer` tailwind class, negative margins, etc) but couldn't come up with a way that wouldn't cause undesired artifacts to occur when hovering, like the following:

<img width="364" alt="Screen Shot 2022-05-27 at 2 18 03 PM" src="https://user-images.githubusercontent.com/393220/171199043-07104764-7f7e-40ba-8e42-b0d44cf3830a.png">

<img width="353" alt="Screen Shot 2022-05-27 at 2 10 06 PM" src="https://user-images.githubusercontent.com/393220/171199087-e28c5f2a-bc49-4fee-afff-f02b2006ef25.png">

<img width="391" alt="Screen Shot 2022-05-27 at 3 21 30 PM" src="https://user-images.githubusercontent.com/393220/171199115-b249357c-7072-4ba9-99d7-270a7b0da4ff.png">

I'm not sure if I handled this additional CSS in the preferred way. Let me know if I should make changes here or if there is a better way we prefer to handle this sort of thing.

2022-05-31 17:16 UTC, 10thfloor commented on libs/design-system/src/lib/Components/LinkCard3Column/LinkCard3Column.stories.tsx
> +    {
Can we add an interface for these?

2022-05-31 17:17 UTC, 10thfloor requested changes
This looks great. One ask is to create an interface for the items in `interfaces.ts` that encodes the structure of the `item`(s) so we can use them in the real application.

2022-06-01 00:31 UTC, alse commented
Good idea adding the custom css for the borders @joekrill. Unfortunately the tailwind peer class applies to all following siblings instead of just the next one.

I renamed it to divided-item-hover, so we can use it with the divide-y helpers in other places: #82

2022-06-01 00:32 UTC, alse approved these changes
👍

2022-06-01 18:00 UTC, 10thfloor commented on libs/design-system/src/lib/Components/LinkCard3Column/LinkCard3Column.stories.tsx
> +    {
I think anything that will be passed as a prop should be an interface, as in the props interface to the component" ... although I'm uncertain when you should use `type` vs `interface` ... Either way, as long as we can statically check our props I'm happy.

2022-06-01 18:00 UTC, merged