28 faq spork page
onflow/next-docs-v1 pull request #95
Opened 2022-06-02 22:30 UTC by neilZon

**Description**
Adds the Spork FAQ Page

closes: #28 

Note: Footer component needs small fix to restyling, will open and tag pr here

2022-06-03 17:07 UTC, 10thfloor requested changes

2022-06-03 17:17 UTC, neilZon commented on libs/design-system/src/lib/Pages/SporkFAQPage/index.tsx
> +          <h1 className="pb-14 font-display text-[44px] font-bold leading-snug md:pb-6 md:font-sans md:text-4xl">
On the Figma doc the font size for this header is 2.75 rem or 44px but the type scale we have in the tailwind config jumps from  `'4xl': ['2rem', { lineHeight: '2.25rem' }]` to `'5xl': ['3.5rem', { lineHeight: '1' }]` which either look too big or too small for the mobile screens compared to the styling

2022-06-03 20:38 UTC, alse commented on libs/design-system/src/lib/Pages/SporkFAQPage/index.tsx
> +          <h1 className="pb-14 font-display text-[44px] font-bold leading-snug md:pb-6 md:font-sans md:text-4xl">
@neilZon I'm seeing 32px on https://www.figma.com/file/704SXr4HrUbIIkXYena62Q/Flow-Dev-Portal-(External)?node-id=1495%3A60231 , which would match the text-4xl size

2022-06-03 20:40 UTC, alse commented on libs/design-system/src/lib/Pages/SporkFAQPage/index.tsx
> +          <button className="mt-2 flex items-center rounded-lg border-primary-blue py-4 text-primary-blue dark:border-primary-purple dark:text-primary-purple md:m-0 md:border md:px-5">
@neilZon I updated the Button component to use left/right icons, you can use it like this after rebasing from main:

```
      <Button variant="secondary" prev={true}>
          Back to Network
      </Button>
      ```

2022-06-03 21:02 UTC, neilZon commented on libs/design-system/src/lib/Pages/SporkFAQPage/index.tsx
> +          <h1 className="pb-14 font-display text-[44px] font-bold leading-snug md:pb-6 md:font-sans md:text-4xl">
@alse I have that for the medium screen styling but on the mobile screen the font size changes https://www.figma.com/file/704SXr4HrUbIIkXYena62Q/Flow-Dev-Portal-(External)?node-id=934%3A30763

2022-06-03 21:24 UTC, alse commented on libs/design-system/src/lib/Pages/SporkFAQPage/index.tsx
> +          <h1 className="pb-14 font-display text-[44px] font-bold leading-snug md:pb-6 md:font-sans md:text-4xl">
Ah cool, I think we can use 4xl on mobile for now to match the other page headers

2022-06-07 16:14 UTC, alse approved these changes

2022-06-07 21:22 UTC, merged